package:
  name: aocxchange
  version: "0.3.0"

source:
  git_rev: 0.3.0
  git_url: https://github.com/floatingpointstack/aoc-xchange.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pythonocc-core
    - aocutils

test:
  imports:
    - aocxchange

about:
  home: https://github.com/floatingpointstack/aoc-xchange
  license: GPL