package:
  name: aocxchange
  version: "18.0.8"

source:
  path: ../aoc-xchange

build:
  number: 0
  noarch: python
  script: python setup.py install
  include_recipe: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - corelib
    - aocutils
    - numpy
    - scipy
    # - OCC
    - wxpython
    - pyqt

about:
  home: https://github.com/guillaume-florent/aoc-xchange
  license: GPLv3
  license_file: LICENSE.txt
  summary: PythonOCC bases CAD files IO